name: Create Netlify site
on: 
  push:
    branches:
      - main

jobs:
  create-netlify-site:
    runs-on: ubuntu-latest
    name: Creating netlify site
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3   
      - name: Use Node.js
        uses: actions/setup-node@v3
   
      - name: Creating netlify site
        uses: ./
        id: create-site
        with:
          unique-site-name: "testap-ak-3234q"
          netlify-team:  ${{ secrets.NETLIFY_TEAM }}
          netlify-token: ${{ secrets.NETLIFY_TOKEN }}
          repo-name: "amitakesai/data-apis-ak"
          branch-name: "development"
      - name: Log URL to the repo
        run: |
          echo "The new repo is ${{ steps.create-site.outputs.site-id }}"
          echo "The new repo is ${{ steps.create-site.outputs.site-url }}"
